default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gather_development

test:
  <<: *default
  database: gather_test

production:
  <<: *default
  database: gather_production
  username: gather
  password: <%= ENV['GATHER_DATABASE_PASSWORD'] %>
