openapi: 3.0.0
info:
  title: Coffee
  description: Coffee
  version: 0.0.1
servers:
  - url: "https://api.coffeecoffeecoffee.coffee"
paths:
  "/groups":
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Group"
  "/groups/{groupId}/events":
    get:
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
components:
  schemas:
    Event:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    Group:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
