openapi: 3.0.0
info:
  title: Coffee
  description: Coffee
  version: 0.0.1
servers:
  - url: "https://coffeecoffeecoffee.coffee/api"
paths:
  "/groups":
    get:
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Group"
  "/groups/{group_id}/events":
    get:
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"
components:
  schemas:
    Event:
      type: object
      required:
        - id
        - group_id
        - name
        - image_url
        - start_at
        - end_at
      properties:
        id:
          type: string
        group_id:
          type: string
        name:
          type: string
        image_url:
          type: string
        start_at:
          type: string
          format: date-time
        end_at:
          type: string
          format: date-time
    Group:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
